# Python Fundamentals Summary

In [3]:
import numpy as np
import pandas as pd

In [4]:
# Create dummy data using NumPy
data = np.array([23, 45, 12, 67, 34, 89, 21])
print("Array:", data)
print("Mean:", np.mean(data))
print("Max:", np.max(data))

Array: [23 45 12 67 34 89 21]
Mean: 41.57142857142857
Max: 89

In [5]:
# Create dummy data using pandas
df = pd.DataFrame({
    "Customer ID": [1, 2, 3, 4],
    " Sales Amount ": [250, 100, 375, 90],
    "Order Date": ["2024-01-05", "2024-02-14", "2024-03-01", "2024-03-22"]
})
df

   Customer ID   Sales Amount   Order Date
0            1             250  2024-01-05
1            2             100  2024-02-14
2            3             375  2024-03-01
3            4              90  2024-03-22

In [7]:
import sys
sys.path.append("../src")

from utils import clean_column_names

In [8]:
# Use the reusable function from utils.py
cleaned_df = clean_column_names(df)
cleaned_df

   customer_id  sales_amount  order_date
0            1           250  2024-01-05
1            2           100  2024-02-14
2            3           375  2024-03-01
3            4            90  2024-03-22

In [10]:
## Function Documentation

**`clean_column_names(df)`**
Takes a pandas DataFrame and standardizes its column names by:
- Converting all letters to lowercase
- Removing extra leading/trailing spaces
- Replacing spaces with underscores

SyntaxError: invalid syntax (2416417348.py, line 3)